name: Run Course Scraper

on:
  schedule:
    - cron: '0 2 15 8 *'   # August 15th at 2:00 AM UTC
    - cron: '0 2 15 12 *'  # December 15th at 2:00 AM UTC
  workflow_dispatch:       # Allows manual triggering of the workflow

jobs:
  run-course-scraper:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'

      - name: Install dependencies
        run: bun install

      - name: Run Course Scraper
        env:
          POCKETBASE_URL: ${{ secrets.POCKETBASE_URL }}
          POCKETBASE_USERNAME: ${{ secrets.POCKETBASE_EMAIL }}
          POCKETBASE_PASSWORD: ${{ secrets.POCKETBASE_PASSWORD }}
          POCKETBASE_ADMIN_USERNAME: ${{ secrets.POCKETBASE_EMAIL }}
          POCKETBASE_ADMIN_PASSWORD: ${{ secrets.POCKETBASE_PASSWORD }}
        run: |
          bun scraper/src/index.ts --function=courses --save --batchSize=100 --offset=0 --term=1040
